### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by vouill** [rlarroque/personal-website#3]
Hello,
I forked your project however i feel the Readme is a bit to weak, there is a lot to say but only a few is related.

Please can you explain you project architecture, your folder tree, the process to follow to install and launch your project, on what version does it compiles  and can you please create a gitter room so we can discuss please.

Thanks

**Comment by Ezwal** [comment]
I agree I was really confused when I first pulled the repo : no explanation whatsoever. This repo could be enhanced by a nicer README !!!
